### ISSUE TITLE
Query deviceManagement/managedDevices fail if filter

### ISSUE THREAD

**Issue by clesieug** [microsoftgraph/microsoft-graph-explorer-v4#3157] opened 2024-05-22 09:45 UTC
**Describe the bug**
Query deviceManagement/managedDevices fail if filter

**To Reproduce**
1. Go to 'graph-explorer'
2. Run query: https://graph.microsoft.com/v1.0/deviceManagement/managedDevices?$filter=deviceName eq 'XXXXXX'

{
    "error": {
        "code": "InternalServerError",
        "message": "{  \"_version\": 3,  \"Message\": \"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 3e43f1c7-dece-dc29-0770-9d1ceae7e86e - Url: https://fef.msub01.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices?api-version=2023-10-19&$filter=deviceName+eq+%27COLAS17328%27\",  \"CustomApiErrorPhrase\": \"\",  \"RetryAfter\": null,  \"ErrorSourceService\": \"\",  \"HttpHeaders\": \"{}\"}",
        "innerError": {
            "date": "2024-05-22T09:41:40",
            "request-id": "e0632382-b271-43e0-97fc-475ae068ed6f",
            "client-request-id": "3e43f1c7-dece-dc29-0770-9d1ceae7e86e"
        }
    }
}

**Comment by musale** [comment] 2024-05-27 08:10
@clesieug I cannot reproduce this on my end, the provided query example works as expected:

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/8081536/c090f4f4-d117-48ce-96b0-3ec4dcf3c069)

Could you retry or run it with a different tenant?

**Comment by clesieug** [comment] 2024-05-27 09:35
Hello Musale
Thank you for your test.
The problem solved itself at the end of the day.
I'm waiting for microsoft to get back to me.
Certainly a problem on one of their endpoint.
Thank you

**Comment by musale** [comment] 2024-05-30 08:38
@clesieug glad to be of help. Open a new issue with the details if it re-occurs. Closing this one.

**Closed by musale** 2024-05-30 08:38 UTC
Labels: ToTriage
