### ISSUE TITLE
Feedback links in Graph Explore do not work

### ISSUE THREAD

**Issue by bruceburge** [microsoftgraph/microsoft-graph-explorer-v4#1564] opened 2022-03-16 13:39 UTC
**Describe the bug**
When using graph explorer after selecting an example, often you will be presented with a item similar to the one below
" Tip - Please provide us with feedback on the groups API here: https://aka.ms/GroupsAPIFeedback."
All of these links resolve something similar to to https://www.bing.com/?ref=aka&shorturl=GroupsAPIFeedback. 
which just shows the default bing home page.

**Comment by ElinorW** [comment] 2022-03-18 09:22
Hey @bruceburge 
I'm currently unable to reproduce this, could you confirm if this is still the behavior you are experiencing

**Comment by bruceburge** [comment] 2022-03-18 09:33
The behavior is not consistent for sure I just test the link on my mobile first time it loaded it went to Bing second time it loaded it went to the form for survey. 

The original issue was on a pc using Firefox and edge, mobile test is Firefox on mobile

![Screenshot_20220318-042733](https://user-images.githubusercontent.com/6773890/158977043-7bfec6d1-9290-49cc-b22e-fbc4eb01774a.png)
![Screenshot_20220318-043056-252](https://user-images.githubusercontent.com/6773890/158977664-e2d0f90e-27ef-4eff-a57a-32b04245d02b.png)

**Comment by ElinorW** [comment] 2022-03-18 12:53
Okay, I'll investigate this

**Comment by ElinorW** [comment] 2022-04-08 09:06
Hey @bruceburge,
Still unable to reproduce this. Perhaps the issue was resolved on the service side. 
Closing this for now, but feel free to re-open if you experience this again

**Closed by ElinorW** 2022-04-08 09:06 UTC
Labels: Status: Needs Investigation, ToTriage

**Comment by bruceburge** [comment] 2022-04-08 14:37
I figured out the issue, The links are case sensitive, and to my knowledge
all lower, a

number of docs have upcase when it should be lower.
