### ISSUE TITLE
graph.microsoft.com/v1.0/teams returns a 404

### ISSUE THREAD

**Issue by MaximRouiller** [microsoftgraph/microsoft-graph-explorer-v4#2171] opened 2022-10-17 14:32 UTC
**Describe the bug**

https://graph.microsoft.com/v1.0/teams returns a 404.

**To Reproduce**

Emit a GET request on that endpoint.

**Expected behavior**

HTTP 200 with some JSON formatted OData payload.

**Screenshots**

<img width="874" alt="image" src="https://user-images.githubusercontent.com/209384/196204592-66f6044a-72fe-4ab9-a61b-c3523235fcca.png">

**Desktop (please complete the following information):**
Does not apply.

**Smartphone (please complete the following information):**
Does not apply.

**Additional context**

It may be related to permissions as the permission tab does not fill up. If it's a permission issue, a 404 should not be returned.

**Comment by ElinorW** [comment] 2022-10-18 09:44
Hey @MaximRouiller, 
I don't think it's a permissions issue since I tried with the beta endpoint and got a permissions error.
Once I enabled the permissions, I got the intended results.
Was this always working on the v1.0 endpoint?
For now, I can only find info about this on the beta endpoint
https://learn.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&tabs=http

**Comment by ElinorW** [comment] 2022-10-18 09:58
Hi @MaximRouiller ,
Hmm, this is interesting.
I can't seem to find anything about GET /teams on the V1.0 docs... But when I try beta, I get results. (https://learn.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&tabs=http)
I don't think it's a permissions issue because when I tried the beta endpoint, I got a permissions error that specified the permissions I needed, then once I consented to one of those, the query successfully ran.

**Comment by ElinorW** [comment] 2022-10-18 10:01
I am going to investigate this a little more...
Some endpoints on the resources list seem to return similar 404 errors

**Comment by RabebOthmani** [comment] 2022-10-18 16:14
@ElinorW could you please share your findings here? @darrelmiller potentially this might be related to OpenAPI

**Comment by ElinorW** [comment] 2022-10-18 18:42
Sure thing @RabebOthmani 
From further investigation, I've noticed this and other errors present on the resources list. 
![image](https://user-images.githubusercontent.com/18407044/196515735-719c2744-0d35-4747-a022-c909e97bf383.png)

This table highlights the endpoints returning errors. These are only one level deep in the resource list. 

It seems like some of these endpoints have been changed or may be invalid. 
For instance the **v1.0/agreementAcceptances** endpoint returns a 404 and when I looked it up on docs is shows as **v1.0/me/agreementAcceptances** ref: https://learn.microsoft.com/en-us/graph/api/user-list-agreementacceptances?view=graph-rest-1.0&tabs=http

**Comment by darrelmiller** [comment] 2022-10-19 14:27
Most of these are failures are "by design".  i.e. the team have not yet implemented the ability to list the collection or retrieve the "api category" singleton.  Teams have finally implemented GET /teams in beta, but it isn't in v1 yet.
In a recent API council meeting we agreed that guidance to teams moving forward would be to return a 405 - Method not implemented, to indicate that you cannot do a GET on the collection.  It is somewhat disappointing to see the array of different responses that we are currently getting.

**Comment by ElinorW** [comment] 2022-10-24 08:36
Yeah the responses are quite varied. 
However, it's great to know that a standard response has been set, and hopefully, we'll see these endpoints conforming to that

**Comment by ElinorW** [comment] 2022-10-24 08:36
I'll close this since there isn't much else to be done on the GE side...

**Closed by ElinorW** 2022-10-24 08:36 UTC
