### ISSUE TITLE
The text "Tenant Sample" disappears when the page is resized

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#2336] opened 2023-01-11 07:18 UTC
**Describe the bug**
The text "Tenant Sample" disappears when the page is resized

https://office.visualstudio.com/OC/_queries/edit/7135035/?triage=true

**Comment by ElinorW** [comment] 2023-01-12 11:44
this has been closed by design.

**Closed by ElinorW** 2023-01-12 11:44 UTC
Labels: ToTriage, Area: Accessibility
