### ISSUE TITLE
InternalServerError on GET /places/microsoft.graph.room

### ISSUE THREAD

**Issue by Avada-Kedavra** [microsoftgraph/microsoft-graph-explorer-v4#1942] opened 2022-07-19 10:14 UTC
**Describe the bug**
I understand `GET /places/microsoft.graph.room` isn't meant to be used for a personal account, but it shouldn't throw an `InternalServerError` in any case. This makes error handling on the client side difficult because we can't tell whether it's because of personal account or an actual issue on Microsoft Graph server.

**To Reproduce**
1. Make a GET request to `https://graph.microsoft.com/v1.0/places/microsoft.graph.room` while signed in as a personal account
2. Server responds with `InternalServerError`

**Expected behavior**
Since this is an issue from the client side, appropriate response would be something like 400 or 404, definitely not 500.

**Screenshots**
![Screenshot 2022-07-19 at 11 12 10](https://user-images.githubusercontent.com/8776011/179726645-86d09b51-418b-4813-b4dc-943b2a2874c8.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS (12.3.1)
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by ElinorW** [comment] 2022-07-21 09:59
Hey @Avada-Kedavra,
We surface the errors that come from the API, it's not really an issue from the client side.

**Comment by Avada-Kedavra** [comment] 2022-07-21 10:06
> Hey @Avada-Kedavra, We surface the errors that come from the API, it's not really an issue from the client side.

Hi @ElinorW! Sorry, let me clarify further. Since this API is not meant to be used by a personal account (as `Places.Read.All` permission isn't supported for personal account), it is a "bad request" from the client side. The best way to make the client know, in my opinion, would be to respond with an appropriate error.

If the client sees internal server error, it's likely to retry until a 20x or 40x response is received. Does that help?

**Comment by ElinorW** [comment] 2022-08-15 16:20
Hey @Avada-Kedavra,
Yes, your clarification definitely helps. 
It seems that the API returns a 500 in cases where the permissions aren't supported for a personal account.
At Graph Explorer we try not to mask the API responses because there could be cases where there is actually a server issue and we report it as a 400 or something which would be wrong. 

I will escalate this with the team as it may require further discussion.

**Comment by ElinorW** [comment] 2022-08-15 16:28
@Avada-Kedavra, 
actually upon further reading... I've learnt that permission errors do result in a 500 response and I believe this is the correct error returned.

**Comment by darrelmiller** [comment] 2022-08-16 14:13
@ElinorW We should never return a 5XX intentionally.  As @Avada-Kedavra  said, this should be a 400 or 404 error.

**Comment by ElinorW** [comment] 2022-08-16 16:26
@darrelmiller okay, thank you for helping me clarify what Graph Explorer should return. 
Should this apply to all 500s or only those related to a personal account?

**Comment by adhiambovivian** [comment] 2022-12-13 11:32
@ElinorW  GE should always return the status code returned by Graph so that the developer experience is uniform across any app/tool that they might be using to access Graph

**Comment by ElinorW** [comment] 2023-01-12 11:53
@adhiambovivian , in that case Graph Explorer does return the status code returned by Graph

**Comment by ElinorW** [comment] 2023-01-16 08:39
I shall be closing this as the responses returned are by design

**Closed by ElinorW** 2023-01-16 08:39 UTC
Labels: API: Graph
