### ISSUE TITLE
Keyboard navigation on permissions tab 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2039] opened 2022-08-15 15:24 UTC
On the permissions tab, when you're using the keyboard to navigate between list items, it's possible to navigate to the 'status' header and when you reach the end on the list, the page scrolling bar takes over 

https://user-images.githubusercontent.com/5781590/184664492-9ae55f73-1891-48a6-a738-4f0401c2458a.mp4

**Comment by Onokaev** [comment] 2022-08-16 14:39
Hey @RabebOthmani. When scrolling through the permissions using the arrow keys and you get to the end of the list, pressing the tab key takes you to the response preview. If you don't press the tab key and continue pressing the down arrow key, the page scrolls. I think this is how it should behave.

What's the expected behavior?

**Comment by thewahome** [comment] 2022-11-08 08:26
Closing this as it seems to be by design. It can be reopened if it still is not expected to work like it does

**Closed by thewahome** 2022-11-08 08:26 UTC
Labels: ToTriage
