### ISSUE TITLE
Invalid filter clause

### ISSUE THREAD

**Issue by frankpeng7** [microsoftgraph/microsoft-graph-explorer-v4#749] opened 2020-10-22 22:50 UTC
**Describe the bug**
I was testing a new API. Somehow it worked in Postman but not in Graph explorer.

In Graph explorer, set the request url to:
```
GET https://graph.microsoft.com/beta/me/onlineMeetings?$filter=JoinWebUrl eq 'https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTM3ODRlODctYjhiMS00MjZkLTkzODItNTk5Y2YyNGQwMzlj%40thread.v2/0?context={"Tid"%3a"909c6581-5130-43e9-88f3-fcb3582cde37"%2c"Oid"%3a"dc17674c-81d9-4adb-bfb2-8f6a442e4622"}'
```
got an error message saying "Invalid filter clause". However, if I copy-paste the **same request url and access token** to Postman, it worked as expected (see screenshots below).

Can you help identify if this is something wrong on Graph explorer's side?

**Screenshots**
Not working in Graph explorer:
![image](https://user-images.githubusercontent.com/16726609/96938133-7b2e5180-147e-11eb-937d-e91a5a2d185f.png)

Same request url and same token in Postman:
![image](https://user-images.githubusercontent.com/16726609/96938178-9600c600-147e-11eb-9841-83dd35cb1635.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [ 86.0.622.48]

**Additional context**
This is from internal. Feel free to reach out on Teams directly.
 
[AB#7468](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7468)

**Comment by thewahome** [comment] 2020-11-02 07:49
Hi @frankpeng7, this should be fixed. Are you still able to reproduce this?

**Comment by ezkemboi** [comment] 2021-02-02 16:50
It seems this is caused by white spaces in the URL. 
As highlighted in #788 and with some fix in #827, this issue might be fixed.

**Comment by ddyett** [comment] 2021-02-08 18:28
@ElinorW can you verify this is fixed and close.

**Comment by ElinorW** [comment] 2021-02-10 07:28
@ezkemboi the spaces in between won't present an issue as they are encoded when the query is run.

**Comment by ezkemboi** [comment] 2021-02-10 07:32
@ElinorW that is true. 
Thanks for clarification.

**Comment by ElinorW** [comment] 2021-02-10 07:41
@frankpeng7 
could you confirm if this is still an issue?
I have tried running a similar query and it works well.
Though I have observed getting the same error when I don't add the `' '` marks surrounding the URL or if I am missing a single one

**Comment by frankpeng7** [comment] 2021-02-10 22:33
Hi @ElinorW yes it's been working for a while. Looks like Graph explorer is now encoding the space.

**Closed** 2021-02-11 07:33 UTC
Labels: Bug – P2
