### ISSUE TITLE
onedrive search not returning results

### ISSUE THREAD

**Issue by anthony1293** [microsoftgraph/microsoft-graph-explorer-v4#2055] opened 2022-08-23 02:59 UTC
**onedrive search only returns blank response.**

1. I have created graph.xlsx in the root folder of my one drive
2. grant permissions for files.readwrite.all and sites.readwrite.all
3. get /v1.0/me/drive/root/search(q='graph.xlsx')?select=name,id,webUrl
4. Response = 200 OK  
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": []
}
5. value is blank.  I can replace the query with any search term and no file details are ever returned.

I would expect to see a response that includes the driveItem details.

If I do /v1.0/me/drive/root/children (get all items in my drive), I receive back all driveItems with details, including the graph.xlsx file I am searching for.

I'm testing in the graph explorer as well as python graph client and get same behavior for both.

**Comment by ElinorW** [comment] 2022-08-23 13:11
hey @anthony1293, 
I'm unable to reproduce this. I have tried something similar and I get a response 
![image](https://user-images.githubusercontent.com/18407044/186166084-8c3164e3-af1b-43a8-9398-fc28820b78c0.png)

Could you confirm if you are still getting a blank response?

**Comment by anthony1293** [comment] 2022-08-23 14:34
but if I do a driveitems search I get a response:
![image](https://user-images.githubusercontent.com/11846825/186186080-26614a87-d748-479c-9fa6-9b4abf67c68a.png)

**Comment by anthony1293** [comment] 2022-08-23 14:44
It's worth noting that the user I have signed into graph explorer with has no admin privileges, so I an only give delegated permissions, no application permissions.

**Comment by ElinorW** [comment] 2022-08-25 08:44
> @ElinorW It's worth noting that the user I have signed into graph explorer with has no admin privileges, so I can only give delegated permissions, no application permissions. Not sure if that would have any effect.

Yeah, I tried this with a user with no admin privileges and it still works. I'll investigate some more

**Comment by ElinorW** [comment] 2022-10-03 15:58
Hey @anthony1293, are you still having trouble this? I'm still unable to reproduce

**Comment by anthony1293** [comment] 2022-10-11 13:58
Hi @Elinor,  yes it's still a problem but it seems to be related to only a specific Tenant.  Using a login for another tenant, and it works ok.

**Comment by ElinorW** [comment] 2022-10-12 08:21
Hey @anthony1293 
Oh okay. Could be a configuration issue... 
I'll close this since it doesn't seem to be a problem specific to Graph Explorer.

**Closed by ElinorW** 2022-10-12 08:21 UTC
Labels: question, Status: Needs Investigation
