### ISSUE TITLE
[Permissions bug] consenting to permissions is not reflected cross browsers 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1499] opened 2022-03-01 13:28 UTC
**Describe the bug**
We received a feedback from a user reporting that when changing permissions, the change is not reflected on the UI between Firefox or Chrome. So I went ahead and tested. 

**To Reproduce**
1. Go to Edge (or any other browser) 
2. On the permissions tab, consent to a permission
3. Go to a different browser (Chrome), make sure you're signed in with the same user
4. Notice on the permissions tab, the change you made on Edge is not there even after refreshing the page

**Screenshots**
![permission consent edge ](https://user-images.githubusercontent.com/5781590/156177493-a3e53d2f-3a0b-4030-9adf-48e0301f51e4.png)

![permission consent ](https://user-images.githubusercontent.com/5781590/156177462-abc4a06b-bf3e-4138-88a4-009fc997c933.png)

**Comment by thewahome** [comment] 2022-03-01 14:04
Does signing out then signing back in have any effect?

**Comment by ddyett** [comment] 2022-08-02 18:34
@RabebOthmani can we close this one, if agreed by design.

**Comment by RabebOthmani** [comment] 2023-01-10 14:09
Picking up this conversation again before we decide which best to do. 
@thewahome @adhiambovivian @gavinbarron @darrelmiller I understand this is done by design but I'm wondering if there's a non costly way to ensure that users get a complete, up to date and relevant information when using Graph Explorer and switching between browsers. Beyond permissions, what happens if a new sample query or resource is added. Would I not be able to see it until I reload my browser or signout/in ?

**Comment by gavinbarron** [comment] 2023-01-17 19:34
AFAIK Samples & resources are somewhat different in that the metadata for those is loaded from the DevX API while the application is loading and therefore should update when a user refreshes their browser.

The data for consented scopes is the response from AAD when a token is requested.  We're using MSAL as a wrapper for our authentication which will use the locally cached token while it is valid. When the access token that the user has expires the subsequent token request will cause the list of consented scopes to be updated.

This feels like a pretty big edge case as it requires a user to be actively using two separate browsers with the same user credentials.

That said, in order to update the list of consented scopes, and in fact the access token being used, in a multiple browser scenario like this we'd need to have some concrete user action in which we could tie some behavior to. Likely we'd have to manually trigger a token fetch ignoring the cache, possibly via a login call.

**Comment by thewahome** [comment] 2023-09-25 12:52
The token is not shared across sessions. The user would need, as mentioned by @gavinbarron, to perform a specific action in the second browser.

**Closed** 2023-10-02 19:27 UTC
Labels: status:needs-discussion, Needs: Author Feedback, Status: No Recent Activity, Area: Permissions
