### ISSUE TITLE
Different response from API returned when using POSTMAN/REST API calls vs Graph Playground

### ISSUE THREAD

**Issue by sunamyagupta** [microsoftgraph/microsoft-graph-explorer-v4#2565] opened 2023-05-09 09:59 UTC
**Describe the bug**
Hi, I was trying to run a certain API, in Graph Developer Playground I`m getting detailed response but when I`m making a REST API call, it is returning different response.

**To Reproduce**
1. Go to 'Developer Playground.'
2. API call - https://graph.microsoft.com/v1.0/users/{user-id}?$expand=manager($levels=max;$select=id,displayName)&$select=id,displayName
3. Detailed response received.
4. Same call via REST API
5. Different response received

**Screenshots**
Data from Playground - 
![image](https://user-images.githubusercontent.com/128042722/237062639-8276b4a8-5ffa-4d58-8e15-359d71779391.png)
Data from REST Call - 
![image](https://user-images.githubusercontent.com/128042722/237062731-ff02bbdd-74c3-49b2-8ddf-d12864dafbac.png)

**Additional context**
Can you help me with why there is data discrepancy between the two?

**Comment by ElinorW** [comment] 2023-05-15 09:17
Hey @sunamyagupta, 
I'm unable to reproduce this. I am getting the same results on Graph Explorer and postman as well. 
Could you confirm whether you are still getting different results?

**Comment by sunamyagupta** [comment] 2023-05-15 10:32
Hi Elinor,

I`m still facing the same issue. Can we connect over a short call to discuss this?

Best Regards,
Sunamya
________________________________

**Comment by ElinorW** [comment] 2023-05-15 12:08
Hey @sunamyagupta, 
I've seen where the problem lies. You are missing the **ConsistencyLevel: eventual** header
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/6c896a02-7c31-4ce7-b4b5-156c2e0f3bf3)
Ref: https://learn.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http#optional-query-parameters

Once you add that to your Postman call, you should get similar results.

**Comment by ElinorW** [comment] 2023-05-15 12:10
Let me know if this works and feel free to close the issue.

**Comment by sunamyagupta** [comment] 2023-05-15 12:18
Hi Elinor,

It worked after this. Thank you so much for your help. I will be closing the thread now 🙂

Best Regards,
Sunamya
________________________________

**Closed** 2023-05-15 12:18 UTC
Labels: Needs: Attention 👋
