### ISSUE TITLE
Outlook Mail SendMail not working (RequestBodyRead) even with graph explorer example

### ISSUE THREAD

**Issue by nandodtx** [microsoftgraph/microsoft-graph-explorer-v4#946] opened 2021-05-11 12:41 UTC
Hello,

I'm trying to deploy a JS application to send some emails. Currently I can't even make it work in Graph Explorer. What I'm doing:

Steps:
1 - Open: https://developer.microsoft.com/en-us/graph/graph-explorer;
2 - Login to my account (organization work account);
3 - Over the examples, Select Outlook Mail tab and then Send an email (POST);
4 - Then I adjust the toRecipients address.
5 - Click Run Query.

Then I'm getting 400 - Bad Request.
{
    "error": {
        "code": "RequestBodyRead",
        "message": "The property 'subject' does not exist on type 'Microsoft.OutlookServices.Message'. Make sure to only use property names that are defined by the type or mark the type as open type. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/.",
        "innerError": {
            "date": "2021-05-11T12:33:55",
            "request-id": "request id",
            "client-request-id": "client request id"
        }
    }
}
![image](https://user-images.githubusercontent.com/42853280/117817306-d7e83280-b23d-11eb-8664-ca45aebf61c9.png)

I checked the permission and seems fine:
![image](https://user-images.githubusercontent.com/42853280/117817031-922b6a00-b23d-11eb-97d5-3e178a3669de.png)

Any comments ?

Thanks in advance!
 
[AB#9379](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9379)

**Comment by Ramon-LibertyPumps** [comment] 2021-05-13 18:50
I get the exact same error message when trying to create a calendar event using the sample queries. If I remove the subject property, it successfully creates the event.

**Comment by Ramon-LibertyPumps** [comment] 2021-06-01 16:19
Now I get a 404 error when trying to create a calendar event or send an email using the presets.

{
    "error": {
        "code": "UnknownError",
        "message": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\"><HTML><HEAD><TITLE>Not Found</TITLE><META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD><BODY><h2>Not Found</h2><hr><p>HTTP Error 404. The requested resource is not found.</p></BODY></HTML>",
        "innerError": {
            "date": "2021-06-01T16:17:06",
            "request-id": "847ce710-57bd-4397-894c-0673a454793a",
            "client-request-id": "20ffa696-d1c2-1f6b-21de-ec50bca816cd"
        }
    }
}

**Comment by kaevne** [comment] 2021-06-01 21:40
@nandodtx your user doesn't exist in the cloud, it exists on-prem so your request went to your on-prem endpoint, which returned the 400.

**Comment by Ramon-LibertyPumps** [comment] 2021-06-04 19:46
Ignore my 404 error. We switched to new routers and set up a Web Application Proxy, instead of NAT'ing our Exchange directly to the Internet. I didn't know that the /api/ directory also has to be published.

However, even after setting that up, we get a gateway timeout. I can see the request come in and the server responds with a 200 in the logs, but the result never makes it back to the Graph Explorer.

When I switch back to NAT, everything works as it should. Not sure how to make this work correctly with WAP.

**Comment by ddyett** [comment] 2021-06-15 17:01
@adhiambovivian can we make sure this gets to the right place?

**Comment by adhiambovivian** [comment] 2021-06-17 07:45
@ddyett  got it!

**Comment by nikithauc** [comment] 2021-06-17 21:12
@MIchaelMainer Do you have any idea about this issue? 

It looks similar to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/450. 

I am unable to reproduce this issue. 
![image](https://user-images.githubusercontent.com/23219007/122472863-f8f71e00-cf75-11eb-8e1b-805d9ed8d82d.png)

**Comment by MIchaelMainer** [comment] 2021-06-17 21:23
@nikithauc  kaevne identified the issue. The user's mailbox is an on-premise mailbox in an organization that has both on-premise and cloud hosted mailboxes. You won't be able to repro until you have a hybrid Exchange organization.

@nandodtx Please see [Requirements for the REST API to work in hybrid deployments](https://docs.microsoft.com/en-us/graph/hybrid-rest-support?view=graph-rest-1.0) and check with your tenant admin. Like the error message stated, hybrid support through the REST API is in preview. Consider asking your tenant admin to migrate your mailbox to Exchange Online.

This is not an issue with Graph Explorer. Closing this issue.

**Closed by MIchaelMainer** 2021-06-17 21:23 UTC
Labels: SDK, ToTriage, question
