### ISSUE TITLE
Renew demo tenant 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1834] opened 2022-06-13 11:59 UTC
Graph Explorer demo tenant needs renewal, this is a high priority item.

**Comment by adhiambovivian** [comment] 2022-06-13 12:15
Duplicate of https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1744

**Closed by adhiambovivian** 2022-06-13 12:16 UTC
Labels: Priority: High
