### ISSUE TITLE
bookingBusinesses beta endpoint does not work anymore

### ISSUE THREAD

**Issue by SbGibson** [microsoftgraph/microsoft-graph-explorer-v4#2760] opened 2023-08-30 13:53 UTC
**Describe the bug**
From this morning retrieving booking businesses through the beta api gives a generic error message.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Select 'beta' version
3. Run https://graph.microsoft.com/beta/bookingBusinesses query

{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2023-08-30T13:43:50",
            "request-id": "2e344a3c-dc17-4b40-ad9a-34fce4e9f634",
            "client-request-id": "2e344a3c-dc17-4b40-ad9a-34fce4e9f634"
        }
    }
}

**Expected behavior**
Based on https://learn.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&tabs=http we expect to receive the list of calendars related to the sample account. Using the v1.0 endpoint https://graph.microsoft.com/v1.0/solutions/bookingBusinesses it works.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5077115/a10bc96a-712e-422a-a52d-633ac8e0c13d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by ElinorW** [comment] 2023-09-06 12:39
Hi @SbGibson ,
Could you confirm whether you're still getting the 500 error response? 
I'm currently unable to reproduce it on my end

**Comment by SbGibson** [comment] 2023-09-06 12:48
> Hi @SbGibson , Could you confirm whether you're still getting the 500 error response? I'm currently unable to reproduce it on my end

Hi Elinor, thanks for replying. 
I can confirm that now that endpoint is working without any change by my side. The problem shifted to other endpoints so I thought it was not a problem of the explorer and filed an issue here https://learn.microsoft.com/en-us/answers/questions/1358994/unknownerror-500-on-different-bookings-beta-endpoi
Dunno if you can do something on that. I let you decide if closing or forwarding this issue to someone else. Many Thanks.

**Comment by ElinorW** [comment] 2023-09-07 07:20
Hey @SbGibson,
I'm glad you were able to file the issue there. The appropriate team should be able to provide more help as we only work on the Graph Explorer application.
I will close this for now.

**Closed by ElinorW** 2023-09-07 07:20 UTC
Labels: Needs: Attention 👋, status:unable-to-reproduce
