### ISSUE TITLE
Graph explorer crashing on test endpoint

### ISSUE THREAD

**Issue by dulcineachau** [microsoftgraph/microsoft-graph-explorer-v4#3102] opened 2024-04-10 21:30 UTC
**Describe the bug**

**To Reproduce**
1. Go to graph explorer
2. Use test endpoint URI - https://canary.graph.microsoft.com/testprodbetaduchaurouting/$metadata
3. Press 'Run Query'
4. See crash

**Expected behavior**
Should see normal request go through with result form AGS.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Tried both Edge and Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by ElinorW** [comment] 2024-04-11 14:55
Hi @dulcineachau , 
This is a duplicate of #3063 and has been resolved. 
The update should be available next week

**Comment by ElinorW** [comment] 2024-04-16 18:15
Hi @dulcineachau,
This is now resolved

**Closed by ElinorW** 2024-04-16 18:15 UTC
Labels: status:duplicate, Needs: Author Feedback
