### ISSUE TITLE
Issue regarding updating MS ToDo Task's status to completed.

### ISSUE THREAD

**Issue by konsultoo-kaushal** [microsoftgraph/microsoft-graph-explorer-v4#2746] opened 2023-08-16 10:23 UTC
**Description**

I am trying to update the Status to 'completed' of Microsoft ToDo's Task using Microsoft Graph REST API v1.0 -> Microsoft To Do API. I am using Python language. but on the status change to 'completed' the task on my MS ToDo will be deleted rather than fall into the list of completed tasks.
The same code was working perfectly 2 months ago but now it is not.
Please provide me with the right guidance.

Regards
- Kaushal Dhamelia

**Comment by ElinorW** [comment] 2023-08-23 11:55
closing as duplicate of #2747

**Closed by ElinorW** 2023-08-23 11:55 UTC
Labels: status:duplicate
