### ISSUE TITLE
Modify Permissions (Preview) Tab is not working, the request is timed out

### ISSUE THREAD

**Issue by longnlp** [microsoftgraph/microsoft-graph-explorer-v4#1035] opened 2021-07-20 20:26 UTC
**Describe the bug**
Modify Permissions (Preview) Tab is not working

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Modify Permissions (Preview)'
3. It is stuck on the loading, and then failed to load the permissions

**Expected behavior**
Load the permission successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/5061372/126390354-f602208e-c2aa-4a18-a0a1-cd0b88ba1e9a.png)
![image](https://user-images.githubusercontent.com/5061372/126390550-c775c50c-17e7-4ec5-abc9-466fb4a54c37.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [edge]
 - Version [Version 93.0.946.1 (Official build) dev (64-bit)]

**Additional context**
Looks like the backend API server is timed out
 
[AB#10312](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10312)

**Comment by reidca** [comment] 2021-07-21 08:15
I am seeing this issue as well. It's resulting in me not being able to use run reports. Any workarounds?

**Comment by thewahome** [comment] 2021-08-31 09:36
This was caused by the autage that happened then. Closing this as the cause of the outage was mitigated

**Closed by thewahome** 2021-08-31 09:36 UTC
Labels: ToTriage, Devx Api
