### ISSUE TITLE
https://graph.microsoft.com/v1.0/oauth2PermissionGrant causes screen to go blank

### ISSUE THREAD

**Issue by LiorLev** [microsoftgraph/microsoft-graph-explorer-v4#3064] opened 2024-03-25 19:00 UTC
**Describe the bug**
As soon as I enter "https://graph.microsoft.com/v1.0/oauth2PermissionGrant" in the URL section of the graph explorer, the broswer screen immediately goes blank (attempted both on edge and chrome in regular and incognito mode). 

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Add the following url in the URL section "https://graph.microsoft.com/v1.0/oauth2PermissionGrant" 
3. See error (screen goes blank

**Expected behavior**
I expected the page to not go blank, so that I can submit my post request,

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18686832/3776f2eb-c476-4bc8-a6aa-43769f974b3b)

**Desktop (please complete the following information):**
 - Browser: edge / chrome 
 - Version: latest of both

**Comment by ElinorW** [comment] 2024-03-26 11:06
duplicate of #3048 
Closing this as the fix is in dev branch and awaiting deployment.

**Closed by ElinorW** 2024-03-26 11:06 UTC
Labels: ToTriage
