### ISSUE TITLE
Graph Explorer crashing 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2024] opened 2022-08-11 09:14 UTC
When signing out/signing in, Graph Explorer is crashing. This is something both @adhiambovivian and myself experienced.

**Comment by Onokaev** [comment] 2022-08-11 11:40
Hey @RabebOthmani. We already created an issue here: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2022

**Comment by Onokaev** [comment] 2022-08-17 13:34
Closing this as it is a duplicate of issue #2022

**Closed by Onokaev** 2022-08-17 13:34 UTC
Labels: ToTriage, Bug – P1
