### ISSUE TITLE
Example query fails with Preview Graph Explorer, succeeds in currently released Graph Explorer

### ISSUE THREAD

**Issue by AlanMcBee** [microsoftgraph/microsoft-graph-explorer-v4#607] opened 2019-12-16 05:28 UTC
I have a query that failed with Graph Explorer Preview (4.0) as of today (2019-12-15), but it works with the non-Preview version (3.0)

Here's the query (note that it requires access to my Mailbox and that I have also registered an open extension, which I am attempting to query:

Sample query:
```
GET https://graph.microsoft.com/v1.0/me/messages/AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A3aKXxhfcfUyzaQyzR06iGwABnaZpXQAA?$expand=extensions($filter=id eq 'name.mcbee.alan.microsoft.devops')
```

Expected response (correct value provided from non-Preview Graph Explorer:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('GUID')/messages(extensions())/$entity",
    "@odata.etag": "W/\"…\"",
    "id": "ID",
    "createdDateTime": "2019-12-05T16:20:33Z",
    "lastModifiedDateTime": "2019-12-05T18:31:33Z",
    "changeKey": "…",
    "categories": [
        "NextAction"
    ],
    "receivedDateTime": "2019-12-05T16:20:34Z",
    "sentDateTime": "2019-12-05T16:20:32Z",
    "hasAttachments": false,
    "internetMessageId": "<…@….namprd21.prod.outlook.com>",
    "subject": "Training For December due 12/19",
    "bodyPreview": "Hi Team,\r\nLooks like we have 2-3 trainings to complete this month …",
    "importance": "high",
    "parentFolderId": "ID",
    "conversationId": "ID",
    "conversationIndex": "ID",
    "isDeliveryReceiptRequested": null,
    "isReadReceiptRequested": false,
    "isRead": true,
    "isDraft": false,
    "webLink": "https://outlook.office365.com/owa/?ItemID=ID&exvsurl=1&viewmodel=ReadMessageItem",
    "inferenceClassification": "focused",
    "body": {
        "contentType": "html",
        "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n…"
    },
    "sender": {
        "emailAddress": {
            "name": "NAME",
            "address": "EMAIL"
        }
    },
    "from": {
        "emailAddress": {
            "name": "NAME",
            "address": "EMAIL"
        }
    },
    "toRecipients": [
        {
            "emailAddress": {
                "name": "NAME",
                "address": "EMAIL"
            }
        }
    ],
    "ccRecipients": [],
    "bccRecipients": [],
    "replyTo": [],
    "flag": {
        "flagStatus": "flagged",
        "dueDateTime": {
            "dateTime": "2019-12-05T08:00:00.0000000",
            "timeZone": "UTC"
        }
    },
    "extensions@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('ID')/messages('ID')/extensions",
    "extensions": [
        {
            "@odata.type": "#microsoft.graph.openTypeExtension",
            "id": "Microsoft.OutlookServices.OpenTypeExtension.name.mcbee.alan.microsoft.devops",
            "extensionName": "name.mcbee.alan.microsoft.devops",
            "WorkItemId": "4086"
        }
    ]
}
```

Actual response by Graph Explorer Preview:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Parsing Select and Expand failed.",
        "innerError": {
            "request-id": "d3fbe5b7-60c7-4aff-b63e-411db1c18144",
            "date": "2019-12-16T04:56:00"
        }
    }
}
```

Response Headers:
```
{
    "cache-control": "private",
    "client-request-id": "GUID",
    "content-length": "229",
    "content-type": "application/json",
    "request-id": "GUID"
}
```

Here are the issued requests from each, captured by Fiddler:

GOOD (3.0)
```
GET https://graph.microsoft.com/v1.0/me/messages/AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A3aKXxhfcfUyzaQyzR06iGwABnaZpXQAA?$expand=extensions($filter=id%20eq%20%27name.mcbee.alan.microsoft.devops%27) HTTP/1.1
Host: graph.microsoft.com
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: https://developer.microsoft.com
Authorization: Bearer ...
Sec-Fetch-Dest: empty
SdkVersion: GraphExplorer/3.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3988.0 Safari/537.36 Edg/81.0.363.0
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: https://developer.microsoft.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
If-None-Match: W/"..."
```

BAD (4.0)
```
GET https://graph.microsoft.com/v1.0/me/messages/AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A3aKXxhfcfUyzaQyzR06iGwABnaZpXQAA?$expand=extensions($filter HTTP/1.1
Host: graph.microsoft.com
Connection: keep-alive
Authorization: Bearer ...
Origin: https://developer.microsoft.com
Sec-Fetch-Dest: empty
SdkVersion: GraphExplorer/4.0, graph-js/2.0.0 (featureUsage=6)
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3988.0 Safari/537.36 Edg/81.0.363.0
client-request-id: 71f5f167-6ca1-561c-6537-c395caa38f46
Accept: */*
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: https://developer.microsoft.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Just on the surface, it looks like 4.0 is truncating the issued request after the **$filter** OData query keyword.

**Comment by ddyett** [comment] 2020-06-26 15:50
duplicate of https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/291.  will track with that one.

**Closed by ddyett** 2020-06-26 15:50 UTC
Labels: SDK Issue, bug, duplicate
