### ISSUE TITLE
Issues reported on the ms-graph-docs repo: Permissions not available in Microsoft Graph Explorer

### ISSUE THREAD

**Issue by lramosvea** [microsoftgraph/microsoft-graph-explorer-v4#2261] opened 2022-11-25 19:03 UTC
Hi Team,

I couldn't use the Transfer option form the ms-graph-docs repo so I am opening this bug here so you can provide an answer.
This is the link to the GitHub issue I am referring to: https://github.com/microsoftgraph/microsoft-graph-docs/issues/19393

Description: Forward this issue to the team that manages Microsoft Graph Explorer saying that the documented permissions are not showing up for request.

**Comment by AlexFilipin** [comment] 2022-11-28 13:23
Hey @fernando-almeida-sprinklr , can you clarify where the permissions are not available?

Are you referring to the "Modify permission" tab that makes some suggestions?

![image](https://user-images.githubusercontent.com/30847504/204287604-7c466d88-b6fe-410a-bd25-51815587ffd0.png)

Agree, seems like they are missing there while on the explicit consent to permissions they show up 

![image](https://user-images.githubusercontent.com/30847504/204287722-033b5d9e-8802-4fe7-b97f-19017b494695.png)

![image](https://user-images.githubusercontent.com/30847504/204288213-adfeb330-3f26-49ef-8058-fd92896f6b0c.png)

Though it seems inconsistent, even in the explicit consent to permissions settings they don't show always up.

Just trying to make sure we are on the same page before the Graph Explorer team looks further into this

**Comment by AlexFilipin** [comment] 2022-11-28 13:26
Permissions: 
- User-LifeCycleInfo.ReadWrite.All
- User-LifeCycleInfo.Read.All

Documented here: https://learn.microsoft.com/en-us/graph/permissions-reference#user-permissions

Relevant for CRUD on user resource type

**Comment by AlexFilipin** [comment] 2022-11-28 13:37
Context: Internal completed permission request was 4396

**Comment by AlexFilipin** [comment] 2022-11-28 13:46
While this is getting triaged from the Graph Explorer team, I also started an internal thread with Jackson Woods and our engineer who worked on getting these permissions published. 

Our publishing process may be missing attention to the "Modify permissions" suggestions of Graph Explorer, for our other recently published permissions [LifecycleWorkflows.Read.All & LifecycleWorkflows.ReadWrite.All] I can see no suggestions are being made either:

![image](https://user-images.githubusercontent.com/30847504/204293124-5ea82e31-89cf-49d3-9ee1-28800ca199d3.png)

**Comment by fernando-almeida-sprinklr** [comment] 2022-11-28 14:32
Hi Alexander,

Based on
https://learn.microsoft.com/en-us/graph/tutorial-lifecycle-workflows-set-employeeleavedatetime
I'd expect that the "Modify permission" tab in Microsoft Graph API Explorer
would present it so I could request it for beta version.
I did check nonetheless that I'm able to add that permission explicitly
though through the associated app registration but my goal was to point out
the issue above.

**Comment by AlexFilipin** [comment] 2022-11-28 14:40
Thanks for confirming @fernando-almeida-sprinklr we will look into the "Modify permission" tab, btw. even in Graph Explorer there is a second place to add permissions beyond the "Modify permission" tab that likely would work already without needing an app reg - just pointing this out as you may not have seen my screenshots above correctly due to responding via email :)

**Comment by fernando-almeida-sprinklr** [comment] 2022-11-28 15:19
Awesome, thanks!

**Comment by AlexFilipin** [comment] 2022-12-05 20:07
Quick update, there is NO issue with the "Modify permissions" suggestions for `/identityGovernance/lifecycleWorkflows` APIs, my screenshot from above was misleading as it was not a valid endpoint URI, all valid endpoints like `/identityGovernance/lifecycleWorkflows/workflows` .

The issue is isolated to User-LifeCycleInfo.ReadWrite.All & User-LifeCycleInfo.Read.All and the GET/PATCH/POST on the user entity.

**Comment by fernando-almeida-sprinklr** [comment] 2022-12-05 22:06
Thanks for the feedback!

**Comment by thewahome** [comment] 2023-02-08 08:05
Closing this since, as mentioned here: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2261#issuecomment-1338099360 there is no issue with the "modify permissions"

**Closed by thewahome** 2023-02-08 08:05 UTC
Labels: Area: Permissions

**Comment by AlexFilipin** [comment] 2023-02-08 11:57
@thewahome there still is an issue for the "modify permissions" tab but it is isolated to User-LifeCycleInfo.ReadWrite.All & User-LifeCycleInfo.Read.All and the GET/PATCH/POST on the user entity. .... its "only" fine for /identityGovernance/lifecycleWorkflows APIs.

![image](https://user-images.githubusercontent.com/30847504/217523174-29f8e601-3844-4269-ba4e-ccedae8e4b1e.png)

The suggestion above should include
- User-LifeCycleInfo.ReadWrite.All
- User-LifeCycleInfo.Read.All

Documented here: https://learn.microsoft.com/en-us/graph/permissions-reference#user-permissions, I guess the crawler is not picking it up because that doc is not behind /graph/api/ ?
